"""games with IP addr

Revision ID: b2ac7533b7dc
Revises: 
Create Date: 2020-09-17 10:36:05.597801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ac7533b7dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('a_allocation', sa.Integer(), nullable=True),
    sa.Column('b_allocation', sa.Integer(), nullable=True),
    sa.Column('c_allocation', sa.Integer(), nullable=True),
    sa.Column('d_allocation', sa.Integer(), nullable=True),
    sa.Column('e_allocation', sa.Integer(), nullable=True),
    sa.Column('f_allocation', sa.Integer(), nullable=True),
    sa.Column('g_allocation', sa.Integer(), nullable=True),
    sa.Column('round', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
